name: Build HPMOR PDFs and eBooks

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:  
  workflow_dispatch:    
  push: 
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-20.04
    steps:

# Initialize
    - name: print start date
      run: |
        date +%Y-%m-%d_%H:%M

    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Python setup
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install requirements
      run: install_requirements.sh

# Build
    - name: Build PDFs
      run: ./make_pdfs.sh

    - name: Build ebooks
      run: ./make_ebooks.sh

# Publish to release       
    - name: Upload to release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: MyPrereleaseTag
        prerelease: true
        files: 
          ./*.pdf
          ebook/output/hpmor.epub
          ebook/output/hpmor.mobi

    - name: print end date
      run: |
        date +%Y-%m-%d_%H:%M
